
spring:
    application:
        name: catalog-service
    h2:
        console:
            enabled: true
            path: /h2

    datasource:
        url: jdbc:h2:file:~/database
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        generate-ddl: true
        defer-datasource-initialization: true   
server:
    port: 8071

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka}
  instance:
    preferIpAddress: true

