
spring:
    application:
        name: customer-service
    h2:
        console:
            enabled: true
            path: /h2

    datasource:
        url: jdbc:h2:file:~/customer-database
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        generate-ddl: true
        defer-datasource-initialization: true   
    data:
        rest:
            base-path: /web/api/v1    
server:
    port: 8072

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka}

