spring:
    application:
        name: eureka-server
    security:
      user:
        name: discUser
        password: discPassword
server:
    port: 8070
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka}